import Head from "next/head";
import { useState } from "react";
import RegisterForm from "../comonents/RegisterForm";
import LoginForm from "../comonents/LoginForm";
import Vault from "../comonents/Vault";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [step, setStep] = useState<"login" | "register" | "vault">("register");

  const renderMain = () => {
    switch (step) {
      case "register":
        return <RegisterForm />;
      case "login":
        return <LoginForm />;
      case "vault":
        return <Vault />;
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{renderMain()}</main>
    </div>
  );
}
