import Head from "next/head";
import { useEffect, useState } from "react";
import RegisterForm from "../comonents/RegisterForm";
import LoginForm from "../comonents/LoginForm";
import Vault from "../comonents/Vault";

import styles from "../styles/Home.module.css";

export type VaultItem = {
  website: string;
  username: string;
  password: string;
};

export type Step = "login" | "register" | "vault";

export default function Home() {
  const [step, setStep] = useState<Step>("register");
  const [vault, setVault] = useState<VaultItem[]>([]);
  const [vaultKey, setVaultKey] = useState<string>("");

  useEffect(() => {
    const vault = window.sessionStorage.getItem("vault");
    const vaultKey = window.sessionStorage.getItem("vaultKey");
    if (vault) setVault(JSON.parse(vault));
    if (vaultKey) {
      setVaultKey(JSON.parse(vaultKey));
      setStep("vault");
    }
    console.log(vault);
  }, []);

  const renderMain = () => {
    switch (step) {
      case "register":
        return <RegisterForm setStep={setStep} setVaultKey={setVaultKey} />;
      case "login":
        return (
          <LoginForm
            setStep={setStep}
            setVault={setVault}
            setVaultKey={setVaultKey}
          />
        );
      case "vault":
        return <Vault vault={vault} vaultKey={vaultKey} />;
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{renderMain()}</main>
    </div>
  );
}
